title: Logic in Agda
  
description: Propositional and fist-order logic developed with the proof assistant Agda.

license: Creative Commons Attribution 4.0 International License
license-file: https://creativecommons.org/licenses/by/4.0/

authors:
  - name: Lorenzo Clemente
    email: clementelorenzo@gmail.com
    corresponding: true
    github_username: lclem

repository: lclem/lia
branch: main

collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
encoding            : "utf-8"
show_dir_listing    : false

plugins:
  - jekyll-toc
  - html-proofer
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
  - jemoji

baseurl: "/lia"
url: ""
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  parse_block_html: true

theme: minima
#theme: alembic-jekyll-theme
excerpt_separator: <!--more-->

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

exclude:
  - "Makefile"
  - "README.md"
  - "*.lagda.md"
  - "*.agdai"
  - "*.agda-lib"
  - "epub/"
  - "src/"
  - "tmp/"
  - "pp/"
  - "agda-stdlib/"
  - "_build/"
  - "docs/"
  - "Guardfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "pp-macros.txt"
  - "spell-checker/"
  - "TODO.md"
  - "*.awk"
  - "*.sh"
  - "ignore/"
  - "*.dep"
  - "*.make"
  - "*.dot"
  - "*.bib"
  - "*.csl"
  - "*#*"
  - "*!*"
  - "*.md.sed"
  - "binder"
  - "thebe/node_modules/"
  - "thebe/src"
  - "thebe/package-lock.json"
  - "thebe/package.json"
  - "thebe/webpack.stats.html"
  - "thebe/babel.config.js"
  - "thebe/CODE_OF_CONDUCT.md"
  - "thebe/development.html"
  - "thebe/docs/"
  - "thebe/e2e/"
  - "thebe/examples"
  - "thebe/index.html"
  - "thebe/jest-puppeteer.config.js"
  - "thebe/jest.config.js"
  - "thebe/jest.e2e.config.js"
  - "thebe/jest.setup.js"
  - "thebe/jupyter-server.js"
  - "thebe/LICENSE"
  - "thebe/README.md"
  - "thebe/test/"
  - "thebe/webpack.config.js"
  - "thebe/tmp"
  - "codemirror-agda/node_modules/"
  - "codemirror-agda/docs"
  - "codemirror-agda/index.html"
  - "codemirror-agda/LICENSE.md"
  - "codemirror-agda/package-lock.json"
  - "codemirror-agda/package.json"
  - "codemirror-agda/README.md"
  - "codemirror-agda/src"
