name: 'build-macos'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: [macos-10.15]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Ls
        run: ls -la pp/src/
      - name: Cache ~/pp
        uses: actions/cache@v1  
        with:
          path: ~/pp
          key: ${{ runner.os }}-${{ matrix.ghc }}-pp
      - name: Cache ~/.cabal/packages
        uses: actions/cache@v1  
        with:
          path: ~/.cabal/packages
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
      - name: Install deps
        run: brew install agda pandoc pandoc-crossref gsed
        # deprecated: pandoc-citeproc
      - name: Install pandoc-numbering
        run: pip3 install pandoc-numbering
      - name: Bundle install
        run: bundle install  
        #agda-mode setup
#      - name: Update cabal
#        run: cabal update
#      - name: Make pp
#        run: cd pp && make 
      - name: make pp executable    
        run: chmod +x pp/pp-macos
      - name: Ls
        run: ls -la pp/src/
#      - name: Install pp
#        run: cd pp && make  install
      - name: Build the book 1
        run: make agda; make agda
      - name: Build the book 2
        run: make docs
#      - name: Add docs
#        run: git add docs
      - name: Git voodoo
        run: git remote update && git fetch --all && git stash && git checkout web && git stash pop && git add .
#git commit -m "${INPUT_COMMIT_MESSAGE}"
#git push --set-upstream origin "${INPUT_BRANCH}"

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          #repository: 'somewhereelse'
          branch: web
          commit_message: Update docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./
