name: 'build'
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Ls
        run: ls -la pp/src/
      - name: Cache ~/.cabal/packages
        uses: actions/cache@v1  
        with:
          path: ~/.cabal/packages
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
      - name: Cache ~/.cabal/store
        uses: actions/cache@v1
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
      - name: Cache dist-newstyle
        uses: actions/cache@v1
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
      - name: Cache ~/.stack
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - name: Cache .stack-work
        uses: actions/cache@v1
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ '**/*.hs' }}
      - name: Install cabal
        run: sudo apt-get install -y cabal-install
      - name: Update cabal
        run: cabal update
      - name: Make pp
        run: cd pp && make 
      - name: Ls
        run: ls -la pp/src/
      - name: Install pp
        run: cd pp && make  install
      - name: Install pandoc
        run: sudo apt-get install -y pandoc pandoc-citeproc
      - name: Install alex
        run: cabal install -y alex
      - name: Install happy
        run: cabal install -y happy
#      - name: Install agda
#        run: sudo apt-get install agda
#      - name: Install agda-mode
#        run: sudo apt-get install agda-mode
#      - name: Install agda-stdlib
#        run: sudo apt-get install agda-stdlib
      - name: Install Agda
        run: cabal install Agda && agda-mode setup
      - name: Build the book 1
        run: make agda; make agda
      - name: Build the book 2
        run: make docs
