name: 'build-macos'
on:
  push:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: [macos-10.15]
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Ls
        run: ls -la pp/src/
      - name: Cache ~/pp
        uses: actions/cache@v1  
        with:
          path: ~/pp
          key: ${{ runner.os }}-${{ matrix.ghc }}-pp
      - name: Cache ~/.cabal/packages
        uses: actions/cache@v1  
        with:
          path: ~/.cabal/packages
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages
      - name: Cache ~/.cabal/store
        uses: actions/cache@v1
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
      - name: Cache dist-newstyle
        uses: actions/cache@v1
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
      - name: Cache ~/.stack
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - name: Cache .stack-work
        uses: actions/cache@v1
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ '**/*.hs' }}
      - name: Install cabal & agda & pandoc
        run: brew install cabal agda pandoc pandoc-citeproc && agda-mode setup
      - name: Update cabal
        run: cabal update
      - name: Make pp
        run: cd pp && make 
      - name: Ls
        run: ls -la pp/src/
      - name: Install pp
        run: cd pp && make  install
      - name: Build the book 1
        run: make agda; make agda
      - name: Build the book 2
        run: make docs
      - name: Add docs
        run: git add docs
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          #repository: 'somewhereelse'
          commit_message: Update docs
